architecture: standalone
replica:
  replicaCount: 0
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.0.11-debian-11-r20
auth:
  enabled: false
  password: ""
master:
  disableCommands: []
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
  configuration: |-
    appendonly no
    save ""
    maxmemory 800mb
    maxmemory-policy volatile-lru
# Disable is Prometheus is not installed
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
